version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" 
    schedule:
      interval: "weekly" # 
      day: "monday" 
      time: "04:00" 
   commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "express"
        versions: ["4.x"]
    labels:
      - "dependencies"
      - "security"
    reviewers:
      - "reviewer1" 
    assignees:
      - "username" 
    open-pull-requests-limit: 100 
